server:
  port: 5012

spring:
  application:
    name: pig-ai-mcp
  ai:
    mcp:
      server:
        name: pig-ai-mcp
        version: 0.1.0

frequency:
  ai:
    app:
      url: http://localhost:5010
  business:
    url: http://localhost:5008
